### ISSUE TITLE
[Sinatra] Fix displaying of the form parameters

### ISSUE THREAD

**Issue by pepe** [LastStar/last-learning-star#2]
Also consider rendering special page, not just in line return of the string.

**Comment by pepe** [comment]
Well I can see the fix anywhere. Please refer this issue in the commit, which will fix this issue. And be sure to clone this repository a make any changes on it.

**Comment by Sidmarek** [comment]
I have problem, how upload (commit) into this branch. I solved this problem in my repository...

**Comment by pepe** [comment]
Well you should clone this repo:
`git clone git@github.com:LastStar/last-learning-star.git`
Then do your work. Then commit with:
`git commit` if you are able, add this issue number with # in the commit message, so it is displayed here.
And finaly push it to GitHub with:
`git push`

**Comment by Sidmarek** [comment]
Warning from github:

Warning: Permanently added 'github.com,192.30.252.130' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

**Comment by pepe** [comment]
Aha, add you ssh public key to GitHub https://help.github.com/articles/generating-ssh-keys
